To use these functions you must first enable the `acme` feature in your app.

== For a new app
Either at creation time you will need to select the `acme` feature

Using the Micronaut CLI select the `acme` feature on creation.

[source,bash]
----
mn create-app --features acme hello-world
----

Or using Micronaut Launch https://micronaut.io/launch/ simply select `acme` feature before downloading your pre-built app.

== For an existing app
Use the micronaut cli to do a `feature-diff` on an exiting app to show the changes needed
to enable the feature.

ex. CLI Feature Diff
[source,bash]
----
cd <project directory>
mn feature-diff --features acme
----

== Creating keypairs

A utility to help with creating keypairs. This is akin to doing something like so with openssl

[source,bash]
----
$ openssl genrsa -out /tmp/mydomain.com-key.pem 4096
----

These keypairs will be used for both ACME accounts as well as each domain will also need its own keypair defined.

Usage:

[source,bash]
----
Usage: mn create-key [-fhvVx] [-k=<keyDir>] -n=<keyName> [-s=<keySize>]
Creates an keypair for use with ACME integration
  -f, --force                Whether to overwrite existing files
  -h, --help                 Show this help message and exit.
  -k, --key-dir=<keyDir>     Custom location on disk to put the key to be used
                               with this account.
                               Default: src/main/resources
  -n, --key-name=<keyName>   Name of the key to be created
  -s, --key-size=<keySize>   Size of the key to be generated
                               Default: 4096
  -v, --verbose              Create verbose output.
  -V, --version              Print version information and exit.
  -x, --stacktrace           Show full stack trace when exceptions occur.
----

== Creating an Account

Creates a new account for a given ACME provider. This command will either create a new account keypair for you or you can pass
the account keypair that you have generated using the `mn create-key` or via `openssl` or other means in as a parameter.

https://certbot.eff.org/[Certbot] or many of the other tools out there can also accomplish this step if you dont want to use this tool.

Usage:

[source,bash]
----
Usage: mn create-acme-account (-u=<serverUrl> | --lets-encrypt-prod | --lets-encrypt-staging)
                              [-fhvVx] -e=<email> [-k=<keyDir>] -n=<keyName> [-s=<keySize>]
Creates a new account on the given ACME server
  -e, --email=<email>        Email address to create account with.
  -f, --force                Whether to overwrite existing files
  -h, --help                 Show this help message and exit.
  -k, --key-dir=<keyDir>     Custom location on disk to put the key to be used with this
                               account.
                               Default: src/main/resources
  -n, --key-name=<keyName>   Name of the key to be created
  -s, --key-size=<keySize>   Size of the key to be generated
                               Default: 4096
  -v, --verbose              Create verbose output.
  -V, --version              Print version information and exit.
  -x, --stacktrace           Show full stack trace when exceptions occur.
ACME server URL
      --lets-encrypt-prod    Use the Let's Encrypt prod URL.
      --lets-encrypt-staging Use the Let's Encrypt staging URL
  -u, --url=<serverUrl>      URL of ACME server to use
----

== Deactivating an Account

Deactivates a given account based on the account key that was used to create the account.

Usage:

[source,bash]
----
Usage: mn deactivate-acme-account (-u=<serverUrl> | --lets-encrypt-prod |
                                  --lets-encrypt-staging) [-fhvVx] [-k=<keyDir>] [-n=<keyName>]
Deactivates an existing ACME account
  -f, --force                Whether to overwrite existing files
  -h, --help                 Show this help message and exit.
  -k, --key-dir=<keyDir>     Directory to find the key to be used for this account.
                               Default: src/main/resources
  -n, --key-name=<keyName>   Name of the key to be used
                               Default: null
  -v, --verbose              Create verbose output.
  -V, --version              Print version information and exit.
  -x, --stacktrace           Show full stack trace when exceptions occur.
ACME server URL
      --lets-encrypt-prod    Use the Let's Encrypt prod URL.
      --lets-encrypt-staging Use the Let's Encrypt staging URL
  -u, --url=<serverUrl>      URL of ACME server to use
----
