[versions]
micronaut-docs = '2.0.0'
micronaut = '4.0.0-M4'
micronaut-test = '4.0.0-M4'

groovy = '4.0.11'
spock = '2.3-groovy-4.0'
testcontainers = "1.18.0"
netty-http3 = "0.0.16.Final"

managed-acme4j = "2.16"
micronaut-serde = "2.0.0-M8"
micronaut-validation = "4.0.0-M7"

[libraries]
managed-acme4j-client = { module = 'org.shredzone.acme4j:acme4j-client', version.ref = 'managed-acme4j' }
managed-acme4j-utils = { module = 'org.shredzone.acme4j:acme4j-utils', version.ref = 'managed-acme4j' }

micronaut-serde = { module = 'io.micronaut.serde:micronaut-serde-bom', version.ref = 'micronaut-serde' }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

graal = { module = "org.graalvm.nativeimage:svm" }
netty-tcnative-boringssl-static = { module = 'io.netty:netty-tcnative-boringssl-static' }
netty-incubator-codec-http3 = { module = "io.netty.incubator:netty-incubator-codec-http3", version.ref = "netty-http3" }
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = 'testcontainers' }

groovy-json = { module = 'org.apache.groovy:groovy-json' }
groovy-dateutil = { module = 'org.apache.groovy:groovy-dateutil' }
