[versions]
managed-acme4j = "2.14"

[libraries]
managed-acme4j-client = { module = 'org.shredzone.acme4j:acme4j-client', version.ref = 'managed-acme4j' }
managed-acme4j-utils = { module = 'org.shredzone.acme4j:acme4j-utils', version.ref = 'managed-acme4j' }

graal = { module = "org.graalvm.nativeimage:svm" }
netty-tcnative-boringssl-static = { module = 'io.netty:netty-tcnative-boringssl-static' }
testcontainers-spock = { module = 'org.testcontainers:spock' }

groovy-json = { module = 'org.apache.groovy:groovy-json' }
groovy-dateutil = { module = 'org.apache.groovy:groovy-dateutil' }
