plugins {
    id "io.micronaut.build.internal.acme-module"
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    implementation(mnValidation.micronaut.validation)
    implementation mn.micronaut.http
    implementation mn.micronaut.retry
    implementation mn.micronaut.http.server
    implementation mn.micronaut.http.server.netty
    implementation libs.managed.acme4j.client
    implementation libs.netty.tcnative.boringssl.static
    compileOnly(mn.micronaut.http.netty.http3)
    testImplementation(mnSerde.micronaut.serde.jackson)
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.testcontainers)
    testImplementation libs.groovy.json
    testImplementation libs.groovy.dateutil
    testImplementation mn.micronaut.http.client
    constraints {
        // Force Bouncy Castle >= 1.84 to fix GHSA-wg6q-6289-32hp and GHSA-c3fc-8qff-9hwx
        implementation(libs.bouncycastle.bcpkix)
        implementation(libs.bouncycastle.bcprov)
    }
}

tasks.withType(Test).configureEach {
    if (System.getenv("TESTCONTAINERS_HOST_OVERRIDE")) {
        systemProperty "jdk.internal.httpclient.disableHostnameVerification", "true"
    }
}
