Utilizing `dns` challenge type allows validation to be done via entry of a DNS TXT record. Currently
the application will log out a message that looks as follows.

.DNS output
[source]
----
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
							CREATE DNS `TXT` ENTRY AS FOLLOWS
				_acme-challenge.example.com with value 79ZNJaxlcLYIFootHL6Rrbh2VUCfFGgPeurVyjoRrS8
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
----

Once this is output you will need to log into your DNS provider and create a TXT entry with the following key and value.

* key: `_acme-challenge.example.com`
* value: `79ZNJaxlcLYIFootHL6Rrbh2VUCfFGgPeurVyjoRrS8`

Since this is a manual process you will also want to bump out your `acme.auth.pause` duration so that there is enough time between retries
and time take for the manual entry/DNS propagation.

[configuration]
----
acme:
  challenge-type: 'dns'
  auth:
    pause: 2m
----

-  Due to the current manual nature in which the dns validation has to be done we change the amount of time we wait before trying to authorize again, to make sure there is time for logging into the dns interface, setting a TXT record and waiting for it to propagate.
