plugins {
    id 'groovy'
    id 'io.micronaut.build.internal.acme-tests'
}

// The examples of the guide, in Groovy (Spock). The Groovy compiler picks up the Micronaut AST transformations
// from the compile classpath.
dependencies {
    testCompileOnly mn.micronaut.inject.groovy

    testImplementation project(":micronaut-acme")
    testImplementation mnTest.micronaut.test.spock

    testRuntimeOnly mnTest.junit.platform.launcher
    testRuntimeOnly mnLogging.logback.classic
}
